apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: oom-tracer
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
  {{- include "chart.annotations" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: oom-tracer
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
