apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: oom-tracer
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "chart.annotations" . | indent 4 }}
