name: release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare build metadata
        id: build_meta
        run: echo "build_date=$(date +%FT%T%z)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
            SHA1=${{ github.sha }}
            BUILDDATE=${{ steps.build_meta.outputs.build_date }}
          tags: |
            ghcr.io/eminaktas/oom-tracer:${{ github.ref_name }}
            ghcr.io/eminaktas/oom-tracer:latest

  chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: chart
          token: ${{ secrets.GITHUB_TOKEN }}
