name: release-chart

on:
  push:
    tags:
      - 'chart-*'

permissions: {}

jobs:
  chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: chart
          token: ${{ secrets.GITHUB_TOKEN }}
